# cuRoboV2 + Mapper tuning parameters

mapper:
  voxel_size: 0.05
  extent_meters_xyz: [2.0, 2.0, 1.5]
  depth_minimum_distance: 0.15
  depth_maximum_distance: 2.0
  min_frames_before_esdf: 5

tf:
  overhead_frame: camera_color_optical_frame
  wrist_frame: wrist_camera_color_optical_frame
  world_frame: base_link

motion_planner:
  robot_config: /ros2_ws/src/team_8/config/ur5_curobo.yml
  max_attempts: 3
